### PR TITLE
bwa-mem: pull from quay.io

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by TMiguelT** [comment]
I can't remember where I derived these CWL files from originally, but it's strange that this is the only one with `sbg` fields and the wrong docker image. Looks like a good fix though, thank you.

**Comment by HadleyKing** [comment]
@TMiguelT I was having the same issue with ALL of the CWL files you used in the tutorial, but just highlighted the BWA as an example. I am sorry if I didn't make that clear.

**Comment by TMiguelT** [comment]
Ah right I understand. I guess at the time I made this, the biocontainers had a `:latest` tag, but they no longer do. I need to update each CWL file with a specific version tag.

**Comment by mr-c** [comment]
Specifically you need to pull from quay.io and pick a tag, yes.

**Pull request merged**
